# Generated by Django 2.2.6 on 2019-11-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('run_days', models.CharField(max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_destination', to='website.Station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_source', to='website.Station')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSeatChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ac', models.IntegerField(verbose_name='1st AC')),
                ('second_ac', models.IntegerField(verbose_name='2nd AC')),
                ('third_ac', models.IntegerField(verbose_name='3rd AC')),
                ('sleeper', models.IntegerField()),
                ('chair_car', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Train')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField()),
                ('distance', models.IntegerField()),
                ('day', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Train')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('pnr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=20)),
                ('journey_date', models.DateField()),
                ('class_type', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('SL', 'SL'), ('CC', 'CC')], max_length=2)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_tickets', to='website.TrainSeatChart')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_destination', to='website.Station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_source', to='website.Station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Train')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others/Not Specified')], max_length=1)),
                ('seat_no', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Ticket')),
            ],
        ),
    ]
