# Generated by Django 2.2.6 on 2019-11-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191107_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='source',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_from',
            field=models.ForeignKey(default='DHN', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_from', to='website.Station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_to',
            field=models.ForeignKey(default='BSB', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_to', to='website.Station'),
            preserve_default=False,
        ),
    ]
